--
-- auradefi 0.1.2: ledger schema for postgresql
--
-- GENERATED by scripts/emit_schema.py from
-- src/auradefi/ledger/backends/models.py. Do not edit by hand: a style gate
-- regenerates this file and fails if it differs.
--
-- Apply it with your own migration tool. auradefi never emits DDL and never
-- opens a connection you did not hand it, so the schema is yours to own.
-- These two tables are simply what the SQL ledger backend reads and writes.
--
-- Only the LEDGER persists. Tenancy, API keys, quota, the audit log, webhook
-- endpoints and embed sync-state are in-memory in this release; there are no
-- tables for them yet, and binding your own store is the way to keep that
-- data (see the Bring your own guide).
--
-- Every numeric column is BIGINT on purpose: timestamps are millisecond
-- epochs, which overflow a 32-bit INTEGER.
--


CREATE TABLE auradefi_ledger_seqs (
	tenant_id VARCHAR NOT NULL, 
	seq BIGINT NOT NULL, 
	PRIMARY KEY (tenant_id)
);

CREATE TABLE auradefi_ledger_transactions (
	tenant_id VARCHAR NOT NULL, 
	id VARCHAR NOT NULL, 
	chain_id VARCHAR NOT NULL, 
	tx_hash VARCHAR NOT NULL, 
	account_id VARCHAR NOT NULL, 
	block_number BIGINT, 
	initiated_at BIGINT NOT NULL, 
	confirmed_at BIGINT, 
	entries_json VARCHAR NOT NULL, 
	removed BOOLEAN NOT NULL, 
	last_modified_seq BIGINT NOT NULL, 
	PRIMARY KEY (tenant_id, id)
);

CREATE INDEX ix_auradefi_ledger_transactions_tenant_seq ON auradefi_ledger_transactions (tenant_id, last_modified_seq);
