"""Emit the ledger schema as plain SQL, one file per dialect.

    python scripts/emit_schema.py            # rewrite docs/schema/*.sql
    python scripts/emit_schema.py --check     # fail if they are stale

`metadata.create_all(engine)` is fine for a script and useless to a team
whose schema is owned by Alembic, Flyway, Liquibase, Prisma, Rails or a
reviewed `.sql` file. Those teams need the DDL as text, in their own
migration, reviewed like any other change — and until now the only way to
get it was to install the package, open a Python REPL and know that
`sqlalchemy.schema.CreateTable` exists.

So it ships as text. The files under `docs/schema/` are generated from the
same `metadata` the library uses, and
`tests/style/test_schema_ddl_is_current.py` regenerates and diffs them, so
a column added in `ledger/backends/models.py` and not reflected here is a
red build rather than a migration that quietly omits a column.

Two dialects: PostgreSQL, because that is what a host running this in
production uses, and SQLite, because that is what the suite exercises.
MySQL is deliberately absent — its `VARCHAR` needs a length in a key, and
choosing lengths is a schema decision nobody has made.
"""

from __future__ import annotations

import sys
from pathlib import Path

from sqlalchemy.dialects import postgresql, sqlite
from sqlalchemy.schema import CreateIndex, CreateTable

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "docs" / "schema"

DIALECTS = {"postgresql": postgresql.dialect(), "sqlite": sqlite.dialect()}

HEADER = """--
-- auradefi {version} — ledger schema for {dialect}
--
-- GENERATED by scripts/emit_schema.py from
-- src/auradefi/ledger/backends/models.py. Do not edit by hand: a style gate
-- regenerates this file and fails if it differs.
--
-- Apply it with your own migration tool. auradefi never emits DDL and never
-- opens a connection you did not hand it, so the schema is yours to own —
-- these two tables are simply what the SQL ledger backend reads and writes.
--
-- Only the LEDGER persists. Tenancy, API keys, quota, the audit log, webhook
-- endpoints and embed sync-state are in-memory in this release; there are no
-- tables for them yet, and binding your own store is the way to keep that
-- data (see the Bring your own guide).
--
-- Every numeric column is BIGINT on purpose: timestamps are millisecond
-- epochs, which overflow a 32-bit INTEGER.
--

"""


def ddl_for(dialect_name: str) -> str:
    """The full CREATE statements for one dialect, tables then indexes."""
    from auradefi import __version__
    from auradefi.ledger.backends.models import metadata

    dialect = DIALECTS[dialect_name]
    parts = [HEADER.format(version=__version__, dialect=dialect_name)]
    for table in metadata.sorted_tables:
        parts.append(str(CreateTable(table).compile(dialect=dialect)).strip() + ";\n")
        for index in sorted(table.indexes, key=lambda item: item.name or ""):
            parts.append(str(CreateIndex(index).compile(dialect=dialect)).strip() + ";\n")
    return "\n".join(parts)


def main() -> int:
    checking = "--check" in sys.argv
    OUT.mkdir(parents=True, exist_ok=True)
    stale: list[str] = []
    for dialect_name in DIALECTS:
        path = OUT / f"ledger_{dialect_name}.sql"
        current = ddl_for(dialect_name)
        if checking:
            existing = path.read_text(encoding="utf-8") if path.exists() else ""
            if existing != current:
                stale.append(str(path.relative_to(REPO)))
            continue
        path.write_text(current, encoding="utf-8")
        print(f"wrote {path.relative_to(REPO)}")
    if stale:
        print("stale schema files — run scripts/emit_schema.py:")
        for name in stale:
            print(f"  {name}")
        return 1
    if checking:
        print("schema files are current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
