"""Client-side search over the built pages: one index file, no service.

Seventy pages with no search is a sidebar and a browser's find-in-page. Every
comparable documentation site has a box in the header, and this is the version
that does not cost the site its two standing promises.

NO THIRD PARTY, NO SERVICE. The index is generated in the same build as the
pages and served from the same origin as a plain classic script, so there is
no CDN, no search backend, no API key and nothing to keep running. A reader
behind a strict CSP gets the pages; a reader whose browser refuses the script
gets a box that does nothing, which is the same as not having one.

WHY A SEPARATE FILE rather than inlined per page. Inlining the index into all
seventy pages would add it seventy times, for roughly half again the size of
the whole site. One file is fetched once and cached, and `<script src>` is
used rather than `fetch()` because a `fetch` of a sibling file is blocked
under `file://`, which the build promises still works.

WHAT IS INDEXED. Title, nav section, the one-line summary, and every H2/H3 on
the page. Not the body text: the index would be most of the corpus, and a
substring hit inside a paragraph ranks a page that mentions a word level with
the page about it. Headings are the compromise, and they are already computed
for the on-this-page outline, so nothing new is parsed.
"""

from __future__ import annotations

import json
import re

#: Rows are arrays, not objects: the keys would repeat once per page and the
#: index is a file every reader downloads.
#:   [path, title, section, summary, headings joined by " "]
_PATH, _TITLE, _SECTION, _SUMMARY, _HEADINGS = range(5)


def _headings(page) -> str:
    """The page's H2 and H3 text, which is what its outline already holds."""
    return " ".join(
        text for level, _anchor, text in page.outline if level in (2, 3)
    )


def index_rows(pages: list) -> list[list[str]]:
    """One row per page, in nav order, skipping pages with no section.

    A page outside every nav section (there are none today) would be
    unreachable from the sidebar too, so leaving it out of search keeps the
    two consistent instead of surfacing something the nav hides.
    """
    return [
        [page.path, page.title, page.section, page.summary or "", _headings(page)]
        for page in pages
        if page.section
    ]


def search_js(pages: list) -> str:
    """`search.js`: the index and the behaviour, as one classic script.

    Written as one file so a page needs one tag and one request. The wiring
    runs on `DOMContentLoaded` rather than immediately, because the script is
    `defer`red and the input it binds to may not exist on a page built before
    this file did.
    """
    rows = json.dumps(index_rows(pages), separators=(",", ":"))
    return (
        "/* Generated by scripts/site_search.py. Do not edit. */\n"
        f"var AURADEFI_PAGES = {rows};\n"
        + _BEHAVIOUR
    )


#: Kept as a module constant rather than built with f-strings: it is full of
#: braces, and every one of them would need doubling.
_BEHAVIOUR = """
(function () {
  var TITLE = 1, SECTION = 2, SUMMARY = 3, HEADINGS = 4;
  var LIMIT = 8;

  function score(row, terms) {
    var total = 0;
    for (var i = 0; i < terms.length; i++) {
      var term = terms[i];
      var hit = 0;
      if (row[TITLE].toLowerCase().indexOf(term) !== -1) hit += 6;
      if (row[SUMMARY].toLowerCase().indexOf(term) !== -1) hit += 3;
      if (row[HEADINGS].toLowerCase().indexOf(term) !== -1) hit += 2;
      if (row[SECTION].toLowerCase().indexOf(term) !== -1) hit += 1;
      // Every term must land somewhere, so "bitcoin price" cannot match a
      // page that only knows about one of the two words.
      if (hit === 0) return 0;
      total += hit;
      if (row[TITLE].toLowerCase().indexOf(term) === 0) total += 4;
    }
    return total;
  }

  function matches(query) {
    var terms = query.toLowerCase().split(/\\s+/).filter(Boolean);
    if (!terms.length) return [];
    var scored = [];
    for (var i = 0; i < AURADEFI_PAGES.length; i++) {
      var value = score(AURADEFI_PAGES[i], terms);
      if (value > 0) scored.push([value, i, AURADEFI_PAGES[i]]);
    }
    // Ties break on the page's nav position, so equal matches come back in
    // reading order instead of whatever the sort happens to do.
    scored.sort(function (a, b) { return b[0] - a[0] || a[1] - b[1]; });
    return scored.slice(0, LIMIT).map(function (entry) { return entry[2]; });
  }

  function wire() {
    var input = document.querySelector(".search input");
    var results = document.querySelector(".search .results");
    if (!input || !results) return;
    var up = input.getAttribute("data-up") || "";
    var open = [];

    function close() {
      results.innerHTML = "";
      results.hidden = true;
      open = [];
    }

    function draw() {
      open = matches(input.value);
      if (!open.length) {
        results.innerHTML = input.value.trim()
          ? '<p class="empty">No page matches that.</p>'
          : "";
        results.hidden = !input.value.trim();
        return;
      }
      var html = "";
      for (var i = 0; i < open.length; i++) {
        var row = open[i];
        html += '<a href="' + up + row[0] + '">'
             + '<span class="hit">' + row[1] + "</span>"
             + '<span class="where">' + row[2] + "</span></a>";
      }
      results.innerHTML = html;
      results.hidden = false;
    }

    input.addEventListener("input", draw);
    input.addEventListener("focus", draw);
    input.addEventListener("keydown", function (event) {
      if (event.key === "Escape") { input.value = ""; close(); input.blur(); }
      if (event.key === "Enter" && open.length) {
        window.location.href = up + open[0][0];
      }
      if (event.key === "ArrowDown") {
        var first = results.querySelector("a");
        if (first) { event.preventDefault(); first.focus(); }
      }
    });
    // A click inside the panel is a click on a result; anywhere else dismisses.
    document.addEventListener("click", function (event) {
      if (!event.target.closest(".search")) close();
    });
    // The shortcut every documentation site has. Skipped while the reader is
    // already typing somewhere, so "/" in a form field stays a slash.
    document.addEventListener("keydown", function (event) {
      if (event.key !== "/" || event.metaKey || event.ctrlKey) return;
      var active = document.activeElement;
      if (active && /^(INPUT|TEXTAREA)$/.test(active.tagName)) return;
      event.preventDefault();
      input.focus();
    });
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", wire);
  } else {
    wire();
  }
})();
"""


def search_html(up: str) -> str:
    """The header control: a labelled input and the panel its results fill.

    `data-up` carries how far the current page sits below the site root, so a
    result link resolves from `books/04_ledger.html` the same way it does from
    the front page. The site is relative-linked throughout for that reason.
    """
    return (
        '<div class="search">'
        '<input type="search" placeholder="Search  /" aria-label="Search the '
        f'documentation" autocomplete="off" data-up="{up}">'
        '<div class="results" hidden></div>'
        "</div>"
    )


def assert_index_is_searchable(pages: list) -> None:
    """Fail the build on an index that would answer nothing.

    An empty or fieldless index is invisible: the box still renders, still
    accepts typing, and reports that nothing matches. That looks identical to
    a working search over a site with no matching page.
    """
    rows = index_rows(pages)
    if len(rows) < 20:
        raise SystemExit(f"search index has only {len(rows)} rows; the site has "
                         f"{len(pages)} pages, so the index is not being built")
    for row in rows:
        if not row[_PATH] or not row[_TITLE]:
            raise SystemExit(f"search index row with no path or title: {row}")
    if not any(row[_HEADINGS] for row in rows):
        raise SystemExit("no page contributed a heading to the search index, so "
                         "only titles are searchable: the outline is not reaching it")
    if not re.search(r"[A-Za-z]", "".join(row[_TITLE] for row in rows)):
        raise SystemExit("search index titles are empty")
